def convert_colors_to_strings_and_shorthand(color_array, colors_already_mapped):
    # Dictionary for color to shorthand mapping
    color_to_shorthand = {
        "thom browne": "tb",
        'thom browne edition': 'tb',
        'wooyoungmi edition': 'wyme',
        'wooyoungmi': 'wyme',
        'bmw m edition': 'bmwe',
'cyberpunk 2077 edition': 'cpe',
'carbon': 'bk',
'quartz': 'wh',
        'rose gold black': 'bk',
        'rose gold white': 'wh',
        'mirror back': 'bk',
'rugged satin': 'bk',
        "mint":'lgn',
        'light green': 'lgn',
        "copper":"br",
                'lunar silver': 'sl',
                'glacier silver': 'sl',
                'pink salmon': 'bl',
                'glacier': 'lbl',
                      "icy blue": "lbl",

'night': 'bl',
'winter mist': 'pp',
'arctic sky': 'lbl',
'astral black': 'bk',

        "rose gold":"rg",
        "black": "bk",
        "blue": "bl",
        "red": "rd",
        "green": "gn",
        "brown": "br",
        "beige": "cr",
        "pink": "pk",
        "gold": "gd",
        "magenta": "pp",
        "purple": "pp",
        "peach": "or",
        "white": "wh",
        "silver": "sl",
        "indigo": "bl",
        "gray": "gy",
        "grey": "gy",
        "blush": "pk",
        "bronze": "br",
        "graphite": "gy",
        "yellow": "yw",
        "navy": "bl",
        "khaki": "gn",
        "sage": "gn",
        "obsidian": "bk",
        "lemongrass": "yw",
        "snow": "wh",
        "hazel": "gn",
        "starlight": "wh",
        "midnight":"bk",
        "charcoal": "bk",
        "chalk": "wh",
        "teal":"bl",
        "aqua":"bl",
        "violet": "pp",
        "cream":"cr",
        "glow": "gl",
        "titanium": "tt",
        "satin coral": "rd",
        "coral": "or",
        "lavender": "pp",
        "ice": "lbl",
        "rose": "pk",
        'lemongrass': 'yw',
        'lime': 'lgn',
        'burgundy': 'br',
        "emerald": "gn",
        "titan":"gy",
        "lake":"bl",
        "orange": "or",
        "mocha":"pp",
    }

   # Splitting the input string by commas and stripping any leading/trailing whitespaces
    colors = [color.strip() for color in color_array.split(",")]

    # Wrapping each original color in quotes
    quoted_colors = ['"{}"'.format(color) for color in colors]

    # Joining the quoted original colors back into a single string
    result_quoted_colors = ", ".join(quoted_colors)

    # Function to find shorthand for a color
    def find_shorthand(color):
        lower_color = color.lower()
        found_colors = [shorthand for color_word, shorthand in color_to_shorthand.items() if color_word in lower_color]
        return found_colors[0] if found_colors else "undefined"

    # Creating key-value pairs for colors and their shorthands with lowercase conversion
    color_shorthand_pairs = {color.lower(): find_shorthand(color) for color in colors}

    # Print statements
    print("\n                     Suitelet:")
    print("                               ")
    print(f":[{result_quoted_colors}],")
    print("===============================")
    
    # Check and print color shorthand key-value pairs
    new_pairs = False
    print("                 ClientScript:")
    print("                               ")
    for color, shorthand in color_shorthand_pairs.items():
        if color not in colors_already_mapped or colors_already_mapped[color] != shorthand:
            print(f"'{color}': '{shorthand}',")
            new_pairs = True

    # If no new pairs were added, print alternative message
    if not new_pairs:
        print("Client side remains unchanged.")
        print("\n ")

# Example usage
colors_already_mapped = {
      "silver": "sl",
      "blue": "bl",
      "gray": "gy",
      "white": "wh",
      "brown": "br",
      "burgundy": "bg",
      "space gray": "sg",
      "graphite": "gy",
      "green": "gn",
      "purple": "pp",
      "red": "rd",
      "l": "pp",
      "o": "or",
      "e": "cr",
      "midnight green": "gn",
      "midnight": "bl",
      "rose gold": "rg",
      "gold": "gd",
      "yellow": "yl",
      "sierra blue": "bl",
      "u": "pp",
      "pacific blue": "bl",
      "pink": "pk",
      "starlight": "wh",
      "jet black": "jb",
      "space grey": "sg",
      "matte midnight green": "gn",
      "t": "tt",
      "y": "yl",
      "a": "gy",
      "n": "bz",
      "r": "rd",
      "mint green": "gn",
      "multi color": "mc",
      "violet": "pp",
      "glow": "gl",
      "black": "bk",
      "grey": "gy",
      "cloud blue": "cbl",
      "mystic bronze": "bz",
      "prism black": "bk",
      "mystic gray": "gy",
      "prism white": "wh",
      "mystic black": "bk",
      "phantom silver": "sl",
      "cosmic gray": "gy",
      "deep purple": "pp",
      "mystic white": "wh",
      "n/a": "undefined",
      "cosmic black": "bk",
      "prism dot black": "bk",
      "jet black": "bk",
      "prism crush black": "bk",
      "greygreen": "gy",
      "space gray": "gy",
      "prism cube black": "bk",
      "prism bricks black": "bk",
      "coral blue": "bl",
      "midnight black": "bk",
      "lilac purple": "pp",
      "cloud navy": "bl",
      "cloud red": "rd",
      "cloud pink": "pk",
      "aura blue": "bl",
      "graphite": "bk",
      "cloud lavender": "pp",
      "phantom black": "bk",
      "awesome black": "bk",
      "awesome blue": "bl",
      "cloud mint": "gn",
      "prism blue": "bl",
      "arctic silver": "sl",
      "titanium gray": "gy",
      "phantom white": "wh",
      "phantom violet": "pp",
      "phantom gray": "gy",
      "phantom pink": "pk",
      "space black": "bk",
      "flamingo pink": "pk",
      "aura black": "bk",
      "aura white": "wh",
      "beige": "cr",
      "aura glow": "gl",
      "ceramic black": "bk",
      "ceramic white": "wh",
      "prism green": "gn",
      "awesome white": "wh",
      "prism bricks blue": "bl",
      "sunrise gold": "gl",
      "cloud white": "wh",
      "orchid gray": "gy",
      "midnight": "bk",
      "pink gold": "pk",
      "prism crush blue": "bl",
      "prism dot gray": "gy",
      "sky blue": "bl",
      "lavender": "pp",
      "cream": "cr",
      "olive": "gn",
      "phantom navy": "bl",
      "phantom brown": "br",
      "mirror black": "bk",
      "mystic green": "gn",
      "crown silver": "sl",
      "cardinal red": "rd",
      "bora purple": "pp",
      "cloud orange": "or",
      "alpine green": "gn",
      "coral": "or",
      "prism crush white": "wh",
      "prism crush silver": "sl",
      "mystic red": "rd",
      "ocean blue": "bl",
      "prism dot white": "wh",
      "bespoke": "undefined",
      "blk": "bk",
      "wht": "wh",
      "gry": "gy",
      "red": "rd",
      "gld": "gd",
      "grn": "gn",
      "slv": "sl",
      "haz": "gn",
      "bu": "bl",
      "vb": "bk",
      "phantom green": "gn",
      'undefined': "undefined",
      "phantom titanium": "tt",
      "deepsea blue": "bl",
      "canary yellow": "yl",
      "maple gold": "gd",
      "lime": "lgn",
      "kinda coral": "or",
      "hazel": "gn",
      "lemongrass": "lgn",
      "sorta seafoam": "gn",
      "sorta sunny": "yl",
      "orange": "or",
      "black red": "bkrd",
      "black gold": "bkgd",
      "bronze blue": "bzbl",
      "icy blue": "lbl",
      "mint": "lgn",
      "thom browne": "tb",
      "black silver": "bksl",
      "nebula black": "bk",
      "awesome graphite": "bk",
      "awesome violet": "pp",
      "star wars": "sw",
      "illusion sunset": "rgl",
      "black titanium": "bk",
      "gray titanium": "gy",
      "golf edition": "glf",
      "volcanic grey": "gy",
      "aurora black": "bk",
      "natural titanium": "tt",
      "interstellar glow": "gl",
      "aquamarine green": "gn",
      "midnight ice": "bk",
      "onyx black": "bk",
      "pac-man edition": "pm",
      "frosted silver": "sl",
      "champagne": "gd",
      "mirror grey": "gy",
      "blue quantum": "bl",
      "meteor gray": "gy",
      "meteor grey": "gy",
      "tungsten gold": "gd",
      "blue titanium": "bl",
      "natural titanium": "tt",
      "illusion sky": "gl",
      "midnight frost": "bl",
      "white titanium": "wh",
      "lavender purple": "pp",
      "aurora gray": "gy",
      "aurora white": "wh",
      "aurora green": "gn",
      "oxford blue": "bl",
      "steel blue": "bl",
      "seafoam green": "gn",
      "titan": "gy",
      "metallic copper": "bz",
      "pure white": "wh",
      "stormy black": "bk",
      "iron gray": "gy",
      "fine gold": "gd",
      "platinum gray": "gy",
      "carmine red": "rd",
      "moroccan blue": "bl",
      "just black": "bk",
      "smoke black": "bk",
      "aura red": "rd",
      "mystic indigo": "bl",
      "graygreen": "gy",
      "raspberry rose": "pk",
      "cloud silver": "sl",
      "lavender violet": "pp",
      "amazing silver": "sl",
      "sapphire blue": "bl",
      "brilliant black": "bk",
      "ice white": "wh",
      "solar red": "rd",
      "almond": "cr",
      "nebula blue": "bl",
      "clearly white": "wh",
      "not pink (very light pink)": "pk",
      "not pink": "pk",
      "morning mist": "sl",
      "stellar black": "bk",
      "moonlight gray": "gy",
      "moonlight gray (dark blue)": "gy",
      "misty blue": "bl",
      "midnight blue": "bl",
      "polished graphite": "bk",
      "blush gold": "gd",
      "liquid mercury": "sl",
      "super black": "bk",
      "lunar gray": "gy",
      "flash gray": "gy",
      "frost white": "wh",
      "peach": "or",
      "capri blue": "bl",
      "khaki": "gn",
      "space black stainless steel": "ssbk",
      "silver stainless steel": "sss",
      "silver stainless steel": "ss",
      "polished silver": "sl",
      "matte black": "bk",
      "mystic silver": "sl",
      "charcoal black": "bk",
      "copper gold": "gd",
      "electric blue": "bl",
      "shimmery white": "wh",
      "cherry red": "rd",
      "black sapphire": "bl",
      "gold platinum": "gd",
      "silver titan": "sl",
      "white pearl": "wh",
      "frosted white": "wh",
      "bronze gold": "gd",
      "blossom pink": "pk",
      "sterling blue": "bl",
      "dark brown": "br",
      "black pearl": "bk",
      "cloudy white": "wh",
      "new platinum gray": "gy",
      "new aurora black": "bk",
      "new moroccan blue": "bl",
      "raspberry rose": "rd",
      "infinite black": "bk",
      "glacier blue": "bl",
      "peach fuzz": "or",
      "viva magenta": "purple",
      "deep indigo": "bl",
      "blush": "pk",
      "lunar grey": "gy",
      "polar silver": "sl",
      "mineral blue": "bl",
      "classy blue": "bl",
      "classy white": "wh",
      "mystic bronze": "br",
      "mystic blue": "bl",
      "mystic grey": "gy",
      "platinum grey": "gy",
      "majestic black": "bk",
      "royal gold": "gd",
      "sorta sage": "gn",
      "obsidian": "bk",
      "snow": "wh",
      "titan gray": "gy",
      "deep sea blue": "bl",
      "star pink": "pk",
      "sleek silver": "sl",
      "dazzling white": "wh",
      "frosted gold": "gd",
      "scuba blue": "bl",
      "chalk": "wh",
      "charcoal": "bk",
      "sage": "gn",
      "camo green": "gn",
      "titanium grey": "gy",
      "ruby red": "rd",
      "burgundy red": "rd",
      "ice blue": "bl",
      "polaris blue": "bl",
      "denim blue": "bl",
      "pearl white": "wh",
      "aqua teal": "bl",
      "mirror purple": "pp",
      "mineral gray": "gy",
      "aqua blue": "bl",
      "satin coral": "rd",
      "noir black": "bk",
      "phantom gold": "gd",
      "phantom red": "rd",
      "thom browne edition": "tb",
      "wooyoungmi edition": "wyme",
      "dream white": "wh",
      "prism crush pink": "pk",
      "cosmic grey": "gy",
      "cloud blue": "bl",
      "barely blue": "lbl",
      "rose pink": "pk",
      "astro black": "bk",
      "ice platinum": "lbl",
      "terra gold": "gd",
      "marine blue": "bl",
      "raspberry rose": "pk",
      "lemongrass": "yw",
      "bmw m edition": "bmwe",
      "paralympic blue": "bl",
      "mocha": "gy",
      "forest green" :"gn",
      "black / silver": "bksl",
      "cosmic emerald": "gn",
      "black sapphire": "bk",
      "green emerald": "gn",
      "blue topaz": "bl",
      "cosmos blue": "bl",
      "stardust white": "wh",
      "interstellar black": "bk",
      "nuit black": "bk",
      "volcanic gray": "gy",
      "dark lake": "bl",
      "twilight blue": "bl",
      "metallic rose": "pk",
      "dark grey": "gy",
      "dark red": "rd",
      "dark green": "gn",
      "orange blue": "bl",
      "lime green": "gn",
      "white frost": "wh",
      "black mist": "bk",
      "arctic blue": "bl",
      "black edition": "bk",
      "metallic copper": "br",
      "alpine white": "wh",
      "chromatic gray": "gy",
      "black/silver": "bk",
      "white/silver": "wh",
      "purple-ish": "pp",
      "blonde rose": "pk",
      "dark gray": "gy",
      "light green": "lgn",
      "oh so orange": "or",
      "merlot red": "rd",
      "rose gold black": "bk",
      "rose gold white": "wh",
      "white silver": "wh",
      "moss green": "gn",
      "coral pink": "pk",
      "mirror back": "bk",
      "rugged satin": "bk",
      "lunar silver": "sl",
      "cyberpunk 2077 edition": "cpe",
      "glacier": "lbl",
      "night": "bl",
      "glacier silver": "sl",
      "carbon gray": "gy",
      "topaz gold": "gd",
      "glacier silver": "sl",
      "camellia red": "rd",
      "winter mist": "pp",
      "arctic sky": "lbl",
      "astral black": "bk",
      "mocha": "pp",
      "black/gray": "gy",
      "black/rose gold": "rg",
      "black/gold": "gd",
      "white/gold": "gd",
      "starry black": "bk",
      "navy blue": "bl",
      "luxe white": "wh",
      "modern beige": "cr",
      "opal blue": "bl",
      "xt2271-5": "moto g play 2023",
      "pink salmon": "bl",
      "carbon": "bk",
      "quartz": "wh",
      "ice": "lbl",
};


# Put the colors here 
input_colors = "Pine Green"

# 
convert_colors_to_strings_and_shorthand(input_colors, colors_already_mapped)
